---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Erick.
--- DateTime: 24/08/2022 16:34
---

---@type ISCollapsableWindow[]
windows = {}

---@param collection ISCollapsableWindow[]
function closeWindows(collection)
    for i, window in ipairs(collection) do
        window:close()
    end
end

---@param object IsoObject
local function OnObjectRightMouseButtonUp( object,  x, y)
    print("******************** INICIO NOVO LOG ********************")
    if object:getContainerCount() > 0 then
        print(object:getContainer():getType())
        if object:getContainer():getType() == "fridge" or object:getContainer():getType() == "fridge_off" then
            print("E uma geladeira")

            closeWindows(windows)

            local mainWindow = ISCollapsableWindow:new(x-125, y-125, 300, 100);
            mainWindow:setVisible(true);

            local btnOn = ISButton:new(0, mainWindow:titleBarHeight(), 20, 20, getText("UI_TURN_ON"))
            local btnOff = ISButton:new(mainWindow:getWidth()-20, mainWindow:titleBarHeight(), 20, 20, getText("UI_TURN_OFF"))

            btnOn:setTitle("On")
            btnOff:setTitle("Off")

            btnOn:initialise()
            btnOn:instantiate()

            btnOff:initialise()
            btnOff:instantiate()

            mainWindow:addChild(btnOn);
            mainWindow:addChild(btnOff);

            mainWindow:addToUIManager()
            windows[1] = mainWindow

        else
            print("Nao e uma geladeira")
        end
    else
        print("Nao tem container")
    end
    print("******************** FIM NOVO LOG ********************")
end

Events.OnObjectRightMouseButtonUp.Add(OnObjectRightMouseButtonUp)
